sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ${database.password}
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJzcSEY45izYsWscbz2
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: touhouqing
  redis:
    host: 43.143.215.162
    port: 6379
    password: ${sky.redis.password}
    database: 0
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
#    mch-id: ${sky.wechat.mch-id}
#    mch-serial-no: ${sky.wechat.mchSerialNo}
#    private-key-file-path: ${sky.wechat.privateKeyFilePath}
#    api-v3-key: ${sky.wechat.apiV3Key}
#    notify-url: ${sky.wechat.notifyUrl}
#    refund-notify-url: ${sky.wechat.refundNotifyUrl}
#    we-chat-pay-cert-file-path: ${sky.wechat.weChatPayCertFilePath}